# Generated by Django 4.2 on 2024-02-19 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Captcha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("captcha", models.CharField(max_length=6, verbose_name="验证码")),
                (
                    "send_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="发送时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.user",
                        verbose_name="邮箱",
                    ),
                ),
            ],
            options={
                "verbose_name": "验证码",
                "verbose_name_plural": "验证码",
            },
        ),
    ]
