# Generated by Django 5.0.3 on 2024-04-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='total_size',
        ),
    ]
