# Generated by Django 4.2 on 2024-02-02 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                ("text", models.TextField(verbose_name="内容")),
                ("storage_size", models.IntegerField(verbose_name="存储大小")),
                (
                    "storage_unit",
                    models.IntegerField(
                        choices=[
                            (1, "B"),
                            (1024, "KB"),
                            (1048576, "MB"),
                            (1073741824, "GB"),
                        ],
                        default=1048576,
                        verbose_name="存储单位",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="价格 (单位：分)")),
                ("max_num", models.IntegerField(default=-1, verbose_name="单用户限制次数")),
                (
                    "valid_time",
                    models.IntegerField(default=-1, verbose_name="有效时间 (-1永久有效)"),
                ),
                ("start_time", models.DateField(verbose_name="开始时间")),
                (
                    "end_time",
                    models.DateField(default="9999-12-31", verbose_name="结束时间"),
                ),
            ],
            options={
                "verbose_name": "订阅",
                "verbose_name_plural": "订阅",
            },
        ),
        migrations.CreateModel(
            name="UserOrders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="订阅时间"),
                ),
                ("is_pay", models.BooleanField(default=False, verbose_name="是否支付")),
                ("pay_time", models.DateTimeField(null=True, verbose_name="支付时间")),
                ("valid_time", models.DateTimeField(null=True, verbose_name="有效时间")),
                ("is_valid", models.BooleanField(default=False, verbose_name="是否有效")),
                ("is_delete", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="pay.menu",
                        verbose_name="订阅内容",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.user",
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户订单",
                "verbose_name_plural": "用户订单",
            },
        ),
    ]
