# Generated by Django 4.2 on 2024-02-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0003_alter_userorders_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userorders",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
