# Generated by Django 4.2 on 2024-02-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0004_alter_userorders_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorders",
            name="notify_id",
            field=models.CharField(max_length=64, null=True, verbose_name="支付宝通知id"),
        ),
    ]
