# Generated by Django 4.2 on 2024-02-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0007_alter_userorders_call_back"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userorders",
            name="notify_id",
        ),
        migrations.AddField(
            model_name="userorders",
            name="trade_no",
            field=models.CharField(max_length=64, null=True, verbose_name="支付宝交易号"),
        ),
    ]
