# Generated by Django 4.2 on 2024-02-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0008_remove_userorders_notify_id_userorders_trade_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userorders",
            name="call_back",
            field=models.TextField(null=True, verbose_name="回调数据"),
        ),
    ]
