# Generated by Django 4.2 on 2024-02-05 07:31

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0009_alter_userorders_call_back"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="text",
            field=mdeditor.fields.MDTextField(verbose_name="内容"),
        ),
    ]
