# Generated by Django 4.2 on 2024-02-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0010_alter_menu_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="storage_unit",
            field=models.BigIntegerField(
                choices=[
                    (1, "B"),
                    (1024, "KB"),
                    (1048576, "MB"),
                    (1073741824, "GB"),
                    (1099511627776, "TB"),
                ],
                default=1073741824,
                verbose_name="存储单位",
            ),
        ),
    ]
