# Generated by Django 5.0.3 on 2024-03-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pay", "0011_alter_menu_storage_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="userorders",
            name="refund",
            field=models.BooleanField(default=False, verbose_name="是否退款"),
        ),
    ]
