# Generated by Django 4.2 on 2024-02-23 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0003_alter_captcha_user"),
        ("file", "0002_alter_fileuser_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("share_code", models.CharField(max_length=16, verbose_name="分享码")),
                ("share_pwd", models.CharField(max_length=16, verbose_name="分享密码")),
                (
                    "share_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="分享时间"),
                ),
                ("share_end_time", models.DateTimeField(verbose_name="分享结束时间")),
                ("is_delete", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "file",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="file.fileuser",
                        verbose_name="分享文件",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.user",
                        verbose_name="分享用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "分享列表",
                "verbose_name_plural": "分享列表",
            },
        ),
    ]
