# Generated by Django 5.0.3 on 2024-03-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharefile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharelist",
            name="share_end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="分享结束时间"),
        ),
        migrations.AlterField(
            model_name="sharelist",
            name="share_pwd",
            field=models.CharField(
                blank=True, max_length=16, null=True, verbose_name="分享密码"
            ),
        ),
    ]
